# Generated by Django 5.2.6 on 2025-09-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteRecipe',
        ),
    ]
